#!/bin/bash
echo "preview build is done"
echo "---Libe---"
echo "---Version 0.0.1---"
echo "Status: Under Development"
build_version="0.0.1"
build_date="2026/6/4"
build_data="src/data"
builder="Poppedque"
echo "build.version = $build_version"
echo "build.date = $build_date"
echo "build.data = $build_data"
echo "builder = $builder"
read -p "Press Enter to continue..."
